# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"

    # provisioning script
    config.vm.provision :shell, path: "../bootstrap_source4x.sh",
      env: {"NAGIOS_VER" => "4.2.4", "NAGIOS_PLUGINS_VER" => "2.1.4"}
    
    # network
    config.vm.network "private_network", ip: "192.168.56.101"
    config.vm.network "forwarded_port", host: 8080, guest: 80
    


    # Configure Virtulbox provider
    config.vm.provider "virtualbox" do |vb, override|

        vb.cpus = 1
        vb.memory = "1024"
        vb.gui = false
        
        # Configure Vagrant plugin, Cachier
        if Vagrant.has_plugin?("vagrant-cachier")
            # https://github.com/fgrehm/vagrant-cachier
            config.cache.scope = :box
        end
            
        # Configure Vagrant plugin, vbguest auto-upgrade
        if Vagrant.has_plugin?("vagrant-vbguest")
            # https://github.com/dotless-de/vagrant-vbguest
            config.vbguest.auto_update = false
        end
    end
end
